### PR TITLE
PWX-40782 | Release helm 4.1.0 for 3.1.7 and 24.2.0

### PR DESCRIPTION
**Pull request by hitesh-wani-px**
**What this PR does / why we need it**:
Release helm 4.1.0 for 3.1.7 and 24.2.0

**Which issue(s) this PR fixes** (optional)
Closes #https://purestorage.atlassian.net/browse/PWX-40782

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Balachandar-Pan** [comment]
We have done sanity
```
[root@ip-10-13-8-162 helmtest]# helm ls -A
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
pxe317  kube-system     1               2024-12-12 09:09:24.845894558 +0000 UTC deployed        portworx-4.1.0  3.1.7

[root@ip-10-13-8-162 helmtest]# kubectl -n kube-system get stc
NAME     CLUSTER UUID                           STATUS    VERSION   AGE
pxbala   4e5bbf0e-89ee-466d-a207-38dce2f665f1   Running   3.1.7     5m59s

[root@ip-10-13-8-162 helmtest]# kubectl -n kube-system get po portworx-operator-bb785bbc6-9rspb -o yaml | grep image
    image: portworx/px-operator:24.2.0
    imagePullPolicy: Always
    image: portworx/px-operator:24.2.0
    imageID: docker-pullable://portworx/px-operator@sha256:9909208f4043a04067c97dadc1a66bc77538478d6be6ccc052e2e19b0fa05188
[root@ip-10-13-8-162 helmtest]#
[root@ip-10-13-8-162 helmtest]# kubectl -n kube-system get po pxbala-546d7 -o yaml | grep image
    image: docker.io/portworx/oci-monitor:3.1.7
    imagePullPolicy: Always
    image: portworx/oci-monitor:3.1.7
    imageID: docker-pullable://portworx/oci-monitor@sha256:fd0253933881438dc03fa232f30ec15aec677140a6e74cb44d43504fefb9866b
[root@ip-10-13-8-162 helmtest]#
[root@ip-10-13-8-162 helmtest]#
[root@ip-10-13-8-162 helmtest]# kubectl -n kube-system get po stork-8d94f547f-dg745 -o yaml | grep image
    image: docker.io/openstorage/stork:24.3.3.1
    imagePullPolicy: Always
    image: openstorage/stork:24.3.3.1
    imageID: docker-pullable://openstorage/stork@sha256:4fbcb126f064f8c440c09ae64b40f1cfdbbcaca5616bdc8601db77f93f483b87
[root@ip-10-13-8-162 helmtest]#

```

**Comment by nikita-bhatia** [comment]
@hitesh-wani-px we are missing new annotation added in 24.2.0 portworx.io/disable-non-disruptive-upgrade with default value true.

**Comment by hitesh-wani-px** [comment]
what is default value for this annotation true or false ?
In code it is mentioned as false 
```
// AnnotationsDisableNonDisruptiveUpgrade [=false] is used to disable smart and parallel kubetnetes node upgrades
AnnotationsDisableNonDisruptiveUpgrade = pxAnnotationPrefix + "/disable-non-disruptive-upgrade"
```

**Comment by nikita-bhatia** [comment]
> AnnotationsDisableNonDisruptiveUpgrade

Actually we should add annotation for following
AnnotationsEnableNonDisruptiveUpgrade with value false of above annotation, because by default when it is not present, then it is considered as disabled. So we need to give a way to customers to enable it.
@svijaykumar-px please confirm the behviour.

**Review by nikita-bhatia — APPROVED** [review]
LGTM

**Pull request merged**
