### PR TITLE
upgrade px to 2.4.0

### PR DESCRIPTION
**Pull request by trierra**
Signed-off-by: trierra <oksana@portworx.com>

**What this PR does / why we need it**:
upgrade px to 2.4.0

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by trierra** [comment]
updated the rbac permissions

**Comment by trierra** [comment]
Good catch. I’ll test it today

Best regards, Oksana Naumov

**Comment by trierra** [comment]
fixed & tested

**Comment by parmarnandish** [comment]
@harsh-px @adityadani  - has this been reviewed and ready to be pushed? We want to upgrade our clusters to 2.4.0 and waiting for this helm update.

**Comment by harsh-px** [comment]
> @harsh-px @adityadani - has this been reviewed and ready to be pushed? We want to upgrade our clusters to 2.4.0 and waiting for this helm update.

@trierra  ^^

**Comment by trierra** [comment]
yes, it was tested and ready to be merged

**Pull request merged**
