### PR TITLE
PWX-40782 | Release helm 5.1.0 for PX 3.2.1 and operator 24.2.0

### PR DESCRIPTION
**Pull request by hitesh-wani-px**
**What this PR does / why we need it**:
Release helm 5.1.0 for PX 3.2.1 and operator 24.2.0

**Which issue(s) this PR fixes** (optional)
Closes #https://purestorage.atlassian.net/browse/PWX-40782

**Special notes for your reviewer**:
We need to approve and merge https://github.com/portworx/helm/pull/672 before merging with this PR

### CODE REVIEW

**Comment by Balachandar-Pan** [comment]
We have performed sanity with supported platform
```
[root@ip-10-13-8-162 ~]# helm ls -A
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/kc40.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/kc40.yaml
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
pxe32x  kube-system     2               2024-12-12 06:10:46.120994725 +0000 UTC deployed        portworx-5.1.0  3.2.1
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]# kubectl -n kube-system get stc
NAME     CLUSTER UUID                           STATUS    VERSION   AGE
pxbala   93fe3285-12a3-4a9e-b57a-7701908b4238   Running   3.2.1     3h27m
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]# kubectl -n kube-system get po -lname=portworx-operator -o yaml | grep image
      image: portworx/px-operator:24.2.0
      imagePullPolicy: Always
      image: portworx/px-operator:24.2.0
      imageID: docker-pullable://portworx/px-operator@sha256:9909208f4043a04067c97dadc1a66bc77538478d6be6ccc052e2e19b0fa05188
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]# kubectl -n kube-system get po -lname=stork -o yaml | grep image
      image: docker.io/openstorage/stork:24.3.3.1
      imagePullPolicy: Always
      image: openstorage/stork:24.3.3.1
      imageID: docker-pullable://openstorage/stork@sha256:4fbcb126f064f8c440c09ae64b40f1cfdbbcaca5616bdc8601db77f93f483b87
      image: docker.io/openstorage/stork:24.3.3.1
      imagePullPolicy: Always
      image: openstorage/stork:24.3.3.1
      imageID: docker-pullable://openstorage/stork@sha256:4fbcb126f064f8c440c09ae64b40f1cfdbbcaca5616bdc8601db77f93f483b87
      image: docker.io/openstorage/stork:24.3.3.1
      imagePullPolicy: Always
      image: openstorage/stork:24.3.3.1
      imageID: docker-pullable://openstorage/stork@sha256:4fbcb126f064f8c440c09ae64b40f1cfdbbcaca5616bdc8601db77f93f483b87
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]#
[root@ip-10-13-8-162 ~]# kubectl -n kube-system get po -lname=portworx -o yaml | grep image
      image: docker.io/portworx/oci-monitor:3.2.1
      imagePullPolicy: Always
      image: portworx/oci-monitor:3.2.1
      imageID: docker-pullable://portworx/oci-monitor@sha256:e7b7d92211685fa8b7911c0c6aed29e4dcdf8e159475ad902adbac3f3b0b92c6
      image: docker.io/portworx/oci-monitor:3.2.1
      imagePullPolicy: Always
      image: portworx/oci-monitor:3.2.1

```

**Comment by nikita-bhatia** [comment]
Similar comment as other PR, we are missing new annotation added in 24.2.0 portworx.io/disable-non-disruptive-upgrade with default value true and health-check annotation, portworx.io/health-check.

**Comment by nikita-bhatia** [comment]
> Similar comment as other PR, we are missing new annotation added in 24.2.0 portworx.io/disable-non-disruptive-upgrade with default value true and health-check annotation, portworx.io/health-check.

**Review by nikita-bhatia — APPROVED** [review]
LGTM

**Pull request merged**
